### ISSUE TITLE
[UX] Upvote and downvote buttons feel unresponsive 

### ISSUE THREAD

**Issue by aggalex** [hjiangsu/thunder#141]
**Description**  
Upvote and Downvote buttons work properly, but they feel sluggish in responsiveness, because the moment the user clicks they don't react immediately.

**How to Reproduce**  
1. Go to main page
2. Click on upvote or downvote

https://github.com/hjiangsu/thunder/assets/11951328/87fc2cd9-6cfd-47dd-84f0-092644ed246b

Similarly

1. Go to main page
2. Swipe any post to the right

And similarly

1. Open a post 
2. Swipe any comment to the right

**Expected Behavior**  
The button should immediately change colour to signify that it's been pressed. 

**Screenshots**  

**Device & App Version:**  
 - Device: POCO M3
 - OS: MIUI 12, Android 11

**Additional Context** 
This is a simple issue to fix. Currently the handling of upvotes and other things follows the following logic upon click (represented using JavaScript promises and an imaginary api):

```js
post.sendUpvote()
    .then(res => res.ok())
    .then(_ => state.upvote = true)
```

It works, but it is but UX cause the delay between the tap and the response in the UI is too long. I suggest something more like this:

```js
state.upvote = true
post.sendUpvote()
    .then(res => res.ok())
    .catch(_ => state.upvote = false)
```

This has the advantage of making the UI response immediate so that the app does not feel as sluggish, but also handling the case of a failed upvote request.

**Comment by hjiangsu** [comment]
I'll add in optimistic updates to posts in the next release!

**Comment by machinaeZER0** [comment]
Yesssss! Oh man, next update is gonna be clutch :D :D :D

**Comment by machinaeZER0** [comment]
Downloaded the latest apk and voting feedback is instantaneous, but I'm getting timeout errors when I do vote:
![Screenshot_20230630-202232](https://github.com/hjiangsu/thunder/assets/3624023/a0087795-43d1-433f-b094-92a4eeaaedac)

That message pops up, goes away, and then pops back up again moments later. Possibly instance related (lemmy.world) and not necessarily app related, but figured I should post in case that was relevant.

I force quit the app and re-opened to see if my vote didn't really go through but it was still there - but I don't know for sure if the vote was really counted, or if the app just thinks it should be (if that makes sense). Trying to upvote a comment produced similar behavior. Let me know if I can provide any more info!

**Comment by hjiangsu** [comment]
This generally should only happen when instances take a long time to respond back - however, I think I fixed the issue of it appearing and disappearing constantly though!

Closing as this should be fixed in v0.2.1+10! Let me know if there are still issues with this

**Comment by machinaeZER0** [comment]
I am still having issues with this, though it's hard to know for sure what should be attributed to the app and what could be attributed to the Lemmy version being used in a given instance :/ When it comes to lemmy.world and lemmy.ml I'm getting timeout errors galore, some happening during the voting process (which then seemingly undoes my vote). 

It feels like the timeout error on voting happens surprisingly quickly compared to the errors I am getting from loading a feed/post - is the wait before timeout a configured amount of time on Thunder's end, or is that coming from Lemmy as a whole? If it's the former, I wonder if waiting a little longer before declaring a timeout might help push a vote through?

**Comment by hjiangsu** [comment]
Does the timeout message keep popping up all the time? Or does it just show up once per action that you take? Each timeout message should only occur once per action, so if it shows up more than once, then there might be a bug where it just constantly shows up

I know `lemmy.world` and `lemmy.ml` are being stressed a lot right now, so any of these actions will cause the timeout issues to be higher than usual

> It feels like the timeout error on voting happens surprisingly quickly compared to the errors I am getting from loading a feed/post - is the wait before timeout a configured amount of time on Thunder's end, or is that coming from Lemmy as a whole?

The timeout is handled on Thunder's end, and its currently set to 5 seconds (which I think should be enough, but I can increase it again to maybe handle these cases)

**Comment by machinaeZER0** [comment]
Sorry if you're getting a lot of feedback that is actually Lemmy version related and not actually a Thunder issue :/ A tricky time for app development, to be sure.

The timeout message was initially popping up multiple times, but I believe your initial changes in either this release or the pre-alpha fixed that - so only getting one instance of the popups now :) When the timeout happens, Thunder visually removes my upvote - you're saying technically it might still be going through, even if I can't see it in the moment?

I wonder how long other apps wait before showing a timeout message... maybe more than five seconds should be given if votes (and other information) can get through based on Lemmy server timeout limits? Like, rather than Thunder timing out with its own set value (5 seconds), should Thunder wait to display a timeout until the Lemmy API returns a "real" one? Is that possible?

(Sorry if I'm using poor terms to brainstorm, this isn't my area of expertise!)

**Comment by hjiangsu** [comment]
> When the timeout happens, Thunder visually removes my upvote - you're saying technically it might still be going through, even if I can't see it in the moment?

If you notice that Thunder visually removes the upvote or downvote, then that usually means the vote didn't go through. For some more information on how it works:

- When you perform a vote action, Thunder immediate changes the status of the post on your end to reflect your action
- At the same time, Thunder sends the request to the instance to perform the upvote or downvote
- If Thunder gets a response back within the timeout, then it updates the vote with the one received from the instance
- Otherwise, it throws an error (the timeout error that you see)
- I would have to dig deeper to see if the instance is able to still update the vote counts after the timeouts happen, but I think it could technically be possible (e.g., Thunder times out after 5 seconds, but the lemmy instance finally responds back 40 seconds lates)

> should Thunder wait to display a timeout until the Lemmy API actually returns a server timeout?

This could be possible but the main thing is that if Thunder waits for lemmy to respond back, it could be a full minute before you would notice a timeout message appear. I'm not too sure how long the timeout is for lemmy instances, but I can imagine the following happens:
- I upvote a post
- I keep scrolling on the feed, and keep upvoting on other posts
- After a minute or so, I finally get back a response from the instance
- The error pops up, but I no longer know which action failed because I upvoted many different ones

Hopefully that clears some things up! :D

**Comment by aggalex** [comment]
It seems like this change is not asynchronous, if an upvote is yet to be ratified, pressing other upvote buttons or sliding posts and comments doesn't respond. I'm not sure whether this is because optimistic voting viewing is not working properly or whether the app is refusing to send any votes at all when a different vote is still in progress.

**steps to reproduce:**
- Send a vote that takes a long time to respond
- Try to send another vote while it's not yet sure if it was sent successfully

**Expected result**
Both votes get shown optimistically, requests are sent in a queue with debouncing and all.

**Actual result**
Second vote doesn't respond optimistically.

**Comment by machinaeZER0** [comment]
> Hopefully that clears some things up! :D

That is helpful, thank you! Yeah, feels like a bit of a tightrope then in terms of (on one hand) not wanting to prematurely time out if there's a chance a vote will go through, while also not waiting so long to display an error that one might no longer know what specifically is erroring. Hmm.
