### ISSUE TITLE
Cannot login to lemmy.world 

### ISSUE THREAD

**Issue by BnjmnBanks** [hjiangsu/thunder#316]
**Description**  

**How to Reproduce**  
1. Go to 'profile icon'
2. Click on 'add account'
3. Do next 'try to login with lemmy.world account'

**Expected Behavior**  
I expect to login but it will not let me.

**Screenshots**  

**Device & App Version:**  
 - Device: [Galaxy S22]
 - OS: [Android 13]
 - Version [0.2.1+11]

**Additional Context**

**Comment by hjiangsu** [comment]
Do you have screenshots of the error? It might help track down the specific issue you're seeing

**Comment by BnjmnBanks** [comment]
I'm sorry, I kinda went screenshot crazy. So I was in the chats I tried
what was recommended. I installed the app and it already has login
information. I go to clear cache and data. Then try to login using the same
exact credentials and it fails.

**Comment by hjiangsu** [comment]
I have an idea of the issue you're having. I'll see if I can get you a temporary build to help address this issue sometime today or tomorrow!

**Comment by BnjmnBanks** [comment]
Thank you boss, I appreciate it.

**Comment by hjiangsu** [comment]
I have released a nightly version which might fix the issues you're seeing! https://github.com/hjiangsu/thunder/releases/tag/v0.2.1-alpha.1%2B12

What I would suggest you to do:
- Clear app data and cache
- Install the new pre-release version
- Remove/log out of your accounts from the app if possible
- Log back in

Let me know if this nightly version fixes the issues! There's also a whole bunch of other additions so feel free to check those out (still in testing, not yet ready for general release)

**Comment by BnjmnBanks** [comment]
It did not work. Still getting the same error. I know lemmy.world was
hacked a day or two ago. Maybe they changed how the login works now.

**Comment by hjiangsu** [comment]
Hmm, could you let me know what the exact error is? Does it have something to do with `userId` or is it a completely different error?

**Comment by BnjmnBanks** [comment]
Same exact error.

**Comment by hjiangsu** [comment]
Could you try this nightly version? https://github.com/hjiangsu/thunder/releases/tag/v0.2.1-alpha.2%2B12

**Comment by BnjmnBanks** [comment]
Just tried it and getting the same error. It's like my account doesn't
exist anymore. I am able to login on though.

**Comment by hjiangsu** [comment]
Dang. I'm not sure what other steps I can take without being able to access the screenshots in question.

Could you maybe forward the screenshots to thunderapp@proton.me via email? If you're not able to use GitHub directly to attach images to?

**Comment by BnjmnBanks** [comment]
Yes I have tried just my screen name, email and lemmy.world email.

**Comment by hjiangsu** [comment]
are you by any chance able to log into another account? is it just the lemmy.world that is not working for you?

**Comment by hjiangsu** [comment]
To clarify - that error usually occurs on the instance's end. The instance returns back that error message and Thunder simple displays that on screen

**Comment by BnjmnBanks** [comment]
I don't know what that means lol. I also don't have another account. I'm
going to make another one. World has been bugging. What's the one I should
sign up for?

**Comment by hjiangsu** [comment]
I think you can try to create another account on another instance to test this out! I dont't particularly have any suggestions, but I've seen `https://lemm.ee/` recently

You can also check out https://join-lemmy.org/instances and find one of the recommended ones there!

**Comment by hjiangsu** [comment]
Closing this issue since it has been resolved
